language: cpp
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: "ppa:jonathonf/ffmpeg-4"
            - sourceline: "ppa:jonathonf/nasm"
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - g++-9
            - nasm
            - libavformat-dev
            - libavcodec-dev
            - libavutil-dev
            - libswscale-dev
      env:
        - MATRIX_EVAL="export CC=gcc-9 && export CXX=g++-9"
    - os: osx
      osx_image: xcode10.2
      

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install -y libfluidsynth-dev

script:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./build-macosx; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./build; fi
